export const chunk6 = [
  { codigo: "6004", denominacao: `IRPJ - PJ Obrigadas ao Lucro Real - Entidades Não Financeiras - Balanço Trimestral`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "6015", denominacao: `IRPF - Ganhos de Capital na Alienação de Bens Imóveis a Vista`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "6020", denominacao: `IRPF - Ganhos de Capital na Alienação de Outros Bens/Direitos a Vista`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "6038", denominacao: `Multa Penal Relacionada à Rede Arrecadadora de Receitas Previdenciárias - Rarp - Lançamento de Ofício`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 10 de 15/03/2019"], dtCriacao: new Date("2019-03-16"), dtExtincao: null, ativo: true },
  { codigo: "6080", denominacao: `Multa pelo Atraso na Entrega da Declaração sobre Operações com Cartões de Crédito (Decred)`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 19 de 23/04/2019"], dtCriacao: new Date("2019-04-24"), dtExtincao: null, ativo: true },
  { codigo: "6100", denominacao: `Multa Isolada por Ausência or Incorreção de Informações Prestadas ao Siscoserv`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 16 de 14/05/2019"], dtCriacao: new Date("2019-05-15"), dtExtincao: null, ativo: true },
  { codigo: "6147", denominacao: `Multa por Falta ou de Atraso na Entrega da Declaração de Transferência de Titularidade de Ações - DTA`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 15 de 14/05/2019"], dtCriacao: new Date("2019-05-15"), dtExtincao: null, ativo: true },
  { codigo: "6186", denominacao: `Multa por Falta ou Atraso na Entrega da Decred - Lançada de Ofício`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 19 de 23/04/2019"], dtCriacao: new Date("2019-04-24"), dtExtincao: null, ativo: true },
  { codigo: "6882", denominacao: `Multa por Falta ou Atraso na Entrega da DIF-Papel Imune - Lançada de Ofício`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 73 de 13/08/2009"], dtCriacao: new Date("2009-08-14"), dtExtincao: null, ativo: true },
  { codigo: "6899", denominacao: `Multa por Atraso na Entrega da Declaração de Operações Imobiliárias (DOI)`, baseLegal: ["INSTRUÇÃO NORMATIVA RFB nº 111 de 15/02/1990", "ATO DECLARATÓRIO EXECUTIVO CORAT nº 87 de 21/11/2006"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "6917", denominacao: `Multa por Omissão/Incorreção de Dados na DOI`, baseLegal: ["INSTRUÇÃO NORMATIVA RFB nº 111 de 15/02/1990"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "6930", denominacao: `Multa Isolada por Arrecadação de Fiança Sem Validade Aduaneira de Admissão Temporária`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7004", denominacao: `Arrecadação sobre Importações Subfaturadas - Multa e Diferença de Impostos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7020", denominacao: `Multa Isolada Aplicada sobre Declarações Aduaneiras do Regime Especial DAC`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7038", denominacao: `Multa Isolada Descumprimento de Requisitos de Entreposto Aduaneiro`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7080", denominacao: `Multa por Embaraço na Fiscalização de Bagagem de Passageiro de Voo Internacional`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7100", denominacao: `Multa do Regime Disciplinar de Despachantes Aduaneiros Corretores e Ajudantes de Despachantes`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7324", denominacao: `CONDECINE - Filmes Estrangeiros para Exibição Comercial e Home Vídeo`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7330", denominacao: `CONDECINE - Filmes Nacionais para Exibição Comercial e Home Vídeo`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7347", denominacao: `CONDECINE - Obras Publicitárias Estrangeiras para TV Aberta/Fechada e Cinema`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7360", denominacao: `CONDECINE - Obras Publicitárias Nacionais para TV Aberta/Fechada e Cinema`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7376", denominacao: `CONDECINE - outras Obras Audiovisuais da Ancine`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7400", denominacao: `CONDECINE - Contribuição para o Desenvolvimento da Indústria Cinematográfica Nacional - Remessas ao Exterior`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 21/12/2010"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7411", denominacao: `CONDECINE - Condecine Telesserviços de Radiodifusão e Comunicações de Ancine`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7423", denominacao: `CONDECINE - Condecine Telesserviços - Lançada de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7430", denominacao: `CONDECINE - Condecine de Conteúdo Audiovisual - outras Remessas Externas`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7441", denominacao: `Ancine - outorga de Direitos Exclusivos de Transmissão de Eventos Esportivos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7453", denominacao: `Ancine - Amortização de Contratos de Financiamento de Projetos Cinematográficos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7467", denominacao: `Arrecadação sobre Propriedade Industrial - Instituto Nacional de Propriedade Industrial - INPI`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7472", denominacao: `Multa pelo Uso Indevido de Marcas e Patentes - INPI`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7485", denominacao: `Arrecadação de Fundo Nacional de Desenvolvimento da Educação - FNDE - Devolução de Saldos de Convênios`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7503", denominacao: `Outorga para Prestação do Serviço de Radiodifusão Sonora e de Sons e Imagens - Comunicações`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7511", denominacao: `Outorga para Prestação do Serviço Telefônico Fixo Comutado - STFC`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7523", denominacao: `Outorga para Prestação de Serviço Móvel Pessoal - SMP`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7530", denominacao: `Outorga para Prestação de Serviço de Comunicação Multimídia - SCM`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7540", denominacao: `Outorga para Exploração de Satélites de Telecomunicações`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7541", denominacao: `Outorga de Concessão de Canal de TV Aberta- Radiodifusores Municipais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7550", denominacao: `Preço Público por Direito de Exploração de Satélite Estrangeiro`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7556", denominacao: `Preço de Autorização para Uso de Radiofrequência do Serviço Móvel Global por Satélite`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7570", denominacao: `Fistel - Taxa de Fiscalização de Funcionamento de Estações de Telecomunicações - Anatel`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7579", denominacao: `Fistel - Taxa de Fiscalização de Instalação de Estações de Telecomunicações - Anatel`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7585", denominacao: `Fistel - outorga de Radiofrequências e de Direito de Exploração do Satélite Nacionais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7590", denominacao: `Fistel - outorga de Radiofrequências e de Direito de Exploração do Satélite - Execuções Intraorçamentárias - Anatel`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7601", denominacao: `Multas Aplicadas pela Anatel Decorrentes de Sanções por Descumprimento de Obrigações Contratuais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7605", denominacao: `Multas da Anatel - Lançadas de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7614", denominacao: `CONDECINE - Radiodifusores de Radiodifusão Comunitária - Ancine`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7619", denominacao: `Fundo de Universalização dos Serviços de Telecomunicações - Fust - Contribuição das Prestadoras de Serviços`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7625", denominacao: `Fust - Contribuição sobre Receita Bruta de Prestadoras de Serviços de Telecomunicações`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7629", denominacao: `Funttel - Fundo para o Desenvolvimento Tecnológico das Telecomunicações - Contribuição de Prestadoras`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7644", denominacao: `Fistel - outorga de Radiofrequência - Lançado de Ofício da PGF`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7650", denominacao: `IPI - Remessa de Bebidas no Atacado por Distribuidor Autorizado`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7882", denominacao: `Adicional de Indenização de Voo - Execução Intraorçamentária`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7899", denominacao: `Royalties Lavras em Terra - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7917", denominacao: `Royalties de Lavras Marítimas - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7930", denominacao: `Participação Especial sobre Exploração de Combustíveis Fósseis Terrestres - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "7939", denominacao: `Participação Especial sobre Exploração de Combustíveis Fósseis Marítimos - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true }
];
