export const chunk7 = [
  { codigo: "7960", denominacao: `CUSTAS JUDICIAIS - JUSTIÇA FEDERAL (DEMAIS COMPONENTES DA PGFN)`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 15 de 21/03/2014"], dtCriacao: new Date("2014-03-24"), dtExtincao: null, ativo: true },
  { codigo: "8000", denominacao: `COFINS - Vendas a Comercial Exportadora - Substituição Tributária`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8008", denominacao: `CONDECINE - Contribuição para o Desenvolvimento da Indústria Cinematográfica Nacional - Condecine Títulos - Ancine`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 24 de 21/03/2014"], dtCriacao: new Date("2014-03-24"), dtExtincao: null, ativo: true },
  { codigo: "8020", denominacao: `R D Ativa - IRPF - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8034", denominacao: `R D Ativa - IRPJ - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8043", denominacao: `R D Ativa - IRRF - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8057", denominacao: `R D Ativa - IPI - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8070", denominacao: `R D Ativa - Impostos sobre a Importação e Operações de Câmbio - Simples Nacional`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8086", denominacao: `R D Ativa - Cofins - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8109", denominacao: `CUSTAS JUDICIAIS - OUTROS RECURSOS COMPROVADOS PELA PGFN`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 15 de 21/03/2014"], dtCriacao: new Date("2014-03-24"), dtExtincao: null, ativo: true },
  { codigo: "8121", denominacao: `PIS/Pasep - Operações de Importação - Operações Intraorçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8128", denominacao: `R D Ativa - CSLL - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8134", denominacao: `R D Ativa - PIS/Pasep - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8140", denominacao: `R D Ativa - ITR - Operações Intra Orçamentárias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8159", denominacao: `CUSTAS JUDICIAIS - OUTROS RECURSOS COMPROVADOS OUTRAS SECRETARIAS`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 15 de 21/03/2014"], dtCriacao: new Date("2014-03-24"), dtExtincao: null, ativo: true },
  { codigo: "8186", denominacao: `Compensação Financeira pela Exploração de Recursos Minerais - CFEM`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8200", denominacao: `IOF - Operações de Crédito - Pessoa Física`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8212", denominacao: `Multa pelo Atraso na Entrega da Escrituração Digital das Obrigações Fiscais Prev e Trab - eSocial`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8220", denominacao: `Multa Ajustada pela Rede Arrecadadora de Receitas Previdenciárias - eSocial`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8231", denominacao: `CONDECINE - Isenção Ancine de Condecine Isenta - Remessas ao Exterior`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8244", denominacao: `CONDECINE - Isenção Ancine de Condecine Isenta - Condecine Títulos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8256", denominacao: `Compensação Financeira por Utilização de Recursos Hídricos para Geração de Energia Elétrica`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8285", denominacao: `Restituição de Convênios do Fundo de Amparo ao Trabalhador - FAT`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8299", denominacao: `IOF - Certificados de Depósito Agropecuário - CDA e Warrants Agropecuários - WA`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8300", denominacao: `Taxa de Serviços Administrativos e Tecnológicos - Suframa - outras Receitas`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8312", denominacao: `Fundo de Amparo ao Trabalhador - FAT - Devolucoes de Restituicoes Incorretas de Seguro Desemprego`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8331", denominacao: `Contribuição ao Fundo Constitucional de Financiamento da Amazônia - FDA - Amortização Contratos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8347", denominacao: `Contribuição ao Fundo Constitucional de Financiamento do Nordeste - FDNE - Amortização Contratos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8360", denominacao: `Contribuição ao Fundo Constitucional de Financiamento do Centro-Oeste - FDCO`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8371", denominacao: `Ancine - outorga de Direitos de Exploração Comercial de Obras Audiovisuais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8388", denominacao: `Ancine - amortização de Financiamento de Ativos de Exibição Cinematográfica`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8394", denominacao: `Fundo Nacional de Segurança Pública - FNSP - Devoluções de Convênios Estaduais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8411", denominacao: `Multas por Descumprimento de Termo de Compromisso Ambiental - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8423", denominacao: `Restabelecimento de Arrendamentos de Áreas sob Domínio SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8430", denominacao: `Alienação de Material Apreendido ou Obsoleto do Comando do Exército`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8441", denominacao: `Restrições de Domínio de Terrenos Concedidos sob Permissão Administrativa - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8453", denominacao: `Pro-Agro - Amortização de Contratos de Financiamento e outros Créditos Securitizados`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8467", denominacao: `Proter - Programa de Terra - Securitização de Créditos Rurais`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8472", denominacao: `IOF - Contrato de Derivativos - Lançado de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8485", denominacao: `COFINS - Diferimento Cumulativo e Não-Cumulativo de Montadoras de Veículos - Lançado de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8490", denominacao: `CSLL - Diferimento de Instituições Financeiras de Créditos e Crédito Imunizado`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8502", denominacao: `PIS/Pasep - Diferimento de Instituições Financeiras de Créditos e Crédito Imunizado`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8531", denominacao: `Cofins - Diferimento de Instituições Financeiras de Créditos e Crédito Imunizado`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8548", denominacao: `Refis - Parcela do Parcelamento Ordinário Lei 9.964/2000 - PF - Lançamento de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8550", denominacao: `Refis - Parcela do Parcelamento Ordinário Lei 9.964/2000 - PJ - Lançamento de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8580", denominacao: `Restituição de Multa de Trânsito Cobrada Indevidamente por outros Estados`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8600", denominacao: `Custas Judiciais da Justiça do Distrito Federal de Competência da PGF`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8619", denominacao: `Custas Judiciais da Justiça do Distrito Federal de Competência de outras Secretarias`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8625", denominacao: `Festa de Rodeio de Peão de Boiadeiro - Contribuição do Plano de Seguridade Social`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8631", denominacao: `Regularização de Depósitos não Previdenciários - Lei nº 9.703/1998 e Lei nº 14.973/2024 - Operações Intraorçamentárias`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAR nº 31 de 14/11/2024"], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8644", denominacao: `Decred - Declaração de Operações com Cartões de Crédito`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8684", denominacao: `Siscoserv - Sistema Integrado de Comércio Exterior de Serviços, Intangíveis e outras Operações`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8882", denominacao: `Devolução de Restituição Indevida - IRPF - Não Tributário`, baseLegal: ["ATO DECLARATÓRIO EXECUTIVO CODAC nº 95 de 01/12/2009", "ATO DECLARATÓRIO EXECUTIVO CODAC nº 25 de 21/03/2013", "ATO DECLARATÓRIO EXECUTIVO CODAC nº 9 o 29/03/2017"], dtCriacao: new Date("2009-12-03"), dtExtincao: null, ativo: true },
  { codigo: "8899", denominacao: `Devolução de Valor de Avaliação in loco de Cursos de Graduação e IES`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8917", denominacao: `Festa de Rodeio de Peão de Boiadeiro - Contribuição Outras Entidades e Fundos`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8930", denominacao: `Laudêmios - Adicional Devido por Direito de Preferência de Alienação - SPU`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8971", denominacao: `Outras Custas Judiciais da Competência de outros Estados`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true },
  { codigo: "8987", denominacao: `Cide - Combustíveis - outras Receitas - Lançado de Ofício`, baseLegal: [], dtCriacao: null, dtExtincao: null, ativo: true }
];
